### ISSUE TITLE
/v2/badge/:shortname/recommendations error

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadger#181]
I'm getting this hitting `/v2/badge/:shortname/recommendations`:

```
/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: Cannot call method 'filter' of undefined
    at Promise.Badge.getSimilar (/Users/mlarsson/Work/checkouts/openbadger/models/badge.js:529:21)
    at Promise.<anonymous> (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:157:8)
    at Promise.EventEmitter.emit (events.js:88:17)
    at Promise.emit (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:79:38)
    at Promise.reject (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:106:15)
    at Promise.error (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/lib/promise.js:89:15)
    at cb (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/lib/query.js:1668:29)
    at exports.tick (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/lib/utils.js:408:16)
    at Cursor.toArray (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:156:22)
    at Cursor.nextObject.self.queryRun (/Users/mlarsson/Work/checkouts/openbadger/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:611:39)
```

**Comment by cmcavoy** [comment]
i think this happens when the badge doesn't have a steam category associated with it. @stenington was able to crash it with test-badge which didn't have a STEAM category. When the STEAM category was added, it stopped crashing.

So...yeah...probably related to incomplete data, but should be more _robust_. Increase the robustness by 15% please.

**Comment by brianloveswords** [comment]
YOU GOT IT, RATCHETING UP THE ROBUSTNESS.

**Comment by threeqube** [comment]
I commented on the PR https://github.com/mozilla/openbadger/issues/200 but fyi, all badges are associated with at least one STEA or M category.
