### ISSUE TITLE
Issue badges by email fails

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#227]
1) configure an issuer account
2) log in as the issuer
3) issue a badge via email

You get a whitescreen and openbadger crashes.

For obvious reasons, this one is high priority.

**Comment by toolness** [comment]
Ok, I think this is being caused because `NODE_ENV=production` on staging/prod and `lib/webhook.js` doesn't check at load time to see if `OPENBADGER_NOTIFICATION_WEBHOOK` is valid. Because of this, `request.post()` is called with a terrible URI and that crashes the process like so:

```
/Users/atul/Documents/mozilla/openbadger/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
Error: options.uri is a required argument
    at Request.init (/Users/atul/Documents/mozilla/openbadger/node_modules/request/main.js:136:11)
    at new Request (/Users/atul/Documents/mozilla/openbadger/node_modules/request/main.js:105:8)
    at request (/Users/atul/Documents/mozilla/openbadger/node_modules/request/main.js:968:11)
    at Function.request.post (/Users/atul/Documents/mozilla/openbadger/node_modules/request/main.js:1021:10)
    at Object.notifyOfReservedClaim (/Users/atul/Documents/mozilla/openbadger/lib/webhooks.js:50:19)
    at Badge.reserveAndNotify (/Users/atul/Documents/mozilla/openbadger/models/badge.js:436:16)
    at done (/Users/atul/Documents/mozilla/openbadger/models/badge.js:335:5)
    at Object.async.until (/Users/atul/Documents/mozilla/openbadger/node_modules/async/lib/async.js:576:13)
    at async.until (/Users/atul/Documents/mozilla/openbadger/node_modules/async/lib/async.js:572:23)
    at Badge.generateClaimCodes (/Users/atul/Documents/mozilla/openbadger/models/badge.js:331:14)
```

So, the solution here, I think, is to simply check `OPENBADGER_NOTIFICATION_WEBHOOK` at startup and ensure that it's a valid URL. If it's not, crash the process immediately (which is what we do with all other types of environment misconfigurations).

**Comment by toolness** [comment]
Ok, I implemented the early warning system, but right now this just means that staging/prod will instantly crash since `OPENBADGER_NOTIFICATION_WEBHOOK` doesn't seem to be set on them. So please set it on them!
