### ISSUE TITLE
Multi-use claim codes crash app

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#262]
am investigating.

**Comment by cmcavoy** [comment]
Crash on openbadger is as such,

```
[2013-06-28T19:04:09.238Z] FATAL: openbadger/3861 on fletch: Cannot read property 'evidence' of null
    TypeError: Cannot read property 'evidence' of null
        at exports.getUnclaimedBadgeInfoFromCode (/home/cmcavoy/Dropbox/projects/openbadger/routes/api.js:387:27)
        at Promise.<anonymous> (/home/cmcavoy/Dropbox/projects/openbadger/routes/api.js:319:5)
        at Promise.onResolve (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
        at Promise.EventEmitter.emit (events.js:96:17)
        at Promise.emit (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:79:38)
        at Promise.fulfill (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:92:20)
        at /home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/lib/query.js:1813:13
        at model.Document.init (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/lib/document.js:243:11)
        at completeOne (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/lib/query.js:1811:10)
        at Query.findOne (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/lib/query.js:1779:11)
  throw err;
        ^
TypeError: Cannot read property 'evidence' of null
    at exports.getUnclaimedBadgeInfoFromCode (/home/cmcavoy/Dropbox/projects/openbadger/routes/api.js:387:27)
    at Promise.<anonymous> (/home/cmcavoy/Dropbox/projects/openbadger/routes/api.js:319:5)
    at Promise.onResolve (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
    at Promise.EventEmitter.emit (events.js:96:17)
    at Promise.emit (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:79:38)
    at Promise.fulfill (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/node_modules/mpromise/lib/promise.js:92:20)
    at /home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/lib/query.js:1813:13
    at model.Document.init (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/lib/document.js:243:11)
    at completeOne (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/lib/query.js:1811:10)
    at Query.findOne (/home/cmcavoy/Dropbox/projects/openbadger/node_modules/mongoose/lib/query.js:1779:11)
```

**Comment by ghost** [comment]
This appears to be happening with claim codes that include uppercase letters.  Should be a pretty easy fix, but need to know whether or not we are supposed to be case-sensitive.  (I suspect the answer is "no")

**Comment by cmcavoy** [comment]
For now, we have a workaround. Nice catch. We should fix it, but it can
wait until Monday.

On Fri, Jun 28, 2013 at 4:09 PM, Erik Christensen
notifications@github.comwrote:

> This appears to be happening with claim codes that include uppercase
> letters. Should be a pretty easy fix, but need to know whether or not we
> are supposed to be case-sensitive. (I suspect the answer is "no")
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/262#issuecomment-20214547
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by ghost** [comment]
Well, I sort of forgot about this one, and we just got another crash in the same spot.  Which way should we go?  Case sensitive claim codes or no?

**Comment by cmcavoy** [comment]
They should be case sensitive.

On Wed, Jul 10, 2013 at 2:25 PM, Erik Christensen
notifications@github.comwrote:

> Well, I sort of forgot about this one, and we just got another crash in
> the same spot. Which way should we go? Case sensitive claim codes or no?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/262#issuecomment-20766530
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com
